#ifndef STATUSDEFS_HPP
#define STATUSDEFS_HPP

enum STATUS_CODE {
	OK,
	CONFIGLOAD_FAILED,
	FORK_FAILED,
	EXEC_FAILED,
	PROCESS_LAUNCHER_FAILED,
	XOPENDISPLAY_FAILED,	
	XLOADFONT_FAILED,
};

#endif //STATUSDEFS_HPP